import { IAccount, ICategory, ILoan, ITransaction } from "@/types/interfaces";

export const mockAccounts: IAccount[] = [
  {
    id: 1,
    name: "Mono black 5402",
    balance: -29775.5,
    type: "CARD",
    currency: "UAH",
    owner: "MARYNA",
    banking: "MONO",
  },
  {
    id: 2,
    name: "Mono white 9831",
    balance: 8150,
    type: "CARD",
    currency: "UAH",
    owner: "MARYNA",
    banking: "MONO",
  },
  {
    id: 3,
    name: "Cash Vanya",
    balance: 140,
    type: "CASH",
    currency: "UAH",
    owner: "IVAN",
  },
  {
    id: 4,
    name: "Pumb",
    balance: -40173.46,
    type: "CARD",
    banking: "PUMB",
    currency: "UAH",
    owner: "IVAN",
  },
];

export const mockCategories: ICategory[] = [
  {
    id: 1,
    name: "Salary",
    icon: "BanknoteArrowDown",
    color: "#009140",
    type: "INCOME",
  },
  {
    id: 2,
    name: "Home",
    icon: "House",
    color: "#0035AD",
    type: "EXPENSE",
  },
  {
    id: 3,
    name: "Parents' help",
    icon: "UsersRound",
    color: "#6B00AD",
    type: "INCOME",
  },
  {
    id: 4,
    name: "Food",
    icon: "Salad",
    color: "#E37D00",
    type: "EXPENSE",
  },
  {
    id: 5,
    name: "Car",
    icon: "CarFront",
    color: "#CFC22B",
    type: "EXPENSE",
  },
];

export const mockTransactions: ITransaction[] = [
  {
    id: 1,
    account_id: 1,
    category_id: 1,
    type: "INCOME",
    amount: 25000,
    description: "Monthly salary",
    date: "2025-10-01T09:00:00",
    currency: "UAH",
  },
  {
    id: 2,
    account_id: 1,
    category_id: 2,
    type: "EXPENSE",
    amount: 140,
    description: "Winston",
    date: "2025-10-02T15:10:00",
    currency: "UAH",
  },
  {
    id: 3,
    account_id: 4,
    category_id: 4,
    type: "EXPENSE",
    amount: 950,
    description: "Groceries at Silpo",
    date: "2025-10-03T18:45:00",
    currency: "UAH",
  },
  {
    id: 4,
    account_id: 2,
    category_id: 2,
    type: "EXPENSE",
    amount: 4200,
    description: "Apartment rent",
    date: "2025-10-05T12:00:00",
    currency: "UAH",
  },
  {
    id: 5,
    account_id: 3,
    category_id: 3,
    type: "INCOME",
    amount: 13200,
    date: "2025-10-10T20:00:00",
    currency: "UAH",
  },
  {
    id: 6,
    account_id: 2,
    type: "TRANSFER",
    amount: 1000,
    description: "Transfer to savings account",
    date: "2025-10-12T09:30:00",
    currency: "UAH",
  },
  {
    id: 7,
    account_id: 2,
    category_id: 2,
    type: "EXPENSE",
    amount: 300,
    description: "Dinner with friends",
    date: "2025-10-15T19:45:00",
    currency: "UAH",
  },
  {
    id: 8,
    account_id: 2,
    category_id: 5,
    type: "EXPENSE",
    amount: 1200,
    description: "Gasoline",
    date: "2025-10-18T14:20:00",
    currency: "UAH",
  },
  {
    id: 9,
    account_id: 1,
    category_id: 1,
    type: "INCOME",
    amount: 500,
    description: "Cashback from Monobank",
    date: "2025-10-20T10:00:00",
    currency: "UAH",
  },
  {
    id: 10,
    account_id: 1,
    category_id: 1,
    type: "INCOME",
    amount: 500,
    description: "Monthly salary",
    date: "2025-10-01T09:00:00",
    currency: "USD",
  },
];

export const mockLoans: ILoan[] = [
  {
    id: 1,
    account_id: 1,
    category_id: 2,
    name: "EcoFlow Delta 2",
    totalAmount: 28000,
    totalPayments: 10,
    monthPaid: 1,
  },
  {
    id: 2,
    account_id: 4,
    category_id: 5,
    name: "Laptop Acer",
    totalAmount: 30000,
    totalPayments: 12,
    monthPaid: 5,
  },
];
